{% set version = "2.13.3" %}

package:
  name: git
  version: {{ version }}

source:
  fn: git-{{ version }}.tar.gz                                                                                                    # [unix]
  url: https://github.com/git/git/archive/v{{ version }}.tar.gz                                                                   # [unix]
  sha256: 6b50ef5a0f886e41d0f969e68274bacfe8ade8bc22954143f7f6f1aab3b62b82                                                        # [unix]
  fn: PortableGit-{{ version }}-32-bit.7z.exe                                                                                     # [win32]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-32-bit.7z.exe  # [win32]
  sha256: a0951eb732808689f9ea78a93e87e1437eee34f7d0657c3d4895820f436ec9ce                                                        # [win32]
  fn: PortableGit-{{ version }}-64-bit.7z.exe                                                                                     # [win64]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
  sha256: 2e6f5ee5b118805f45b19aee57f4e138886714a2162bca229640111635efb4b7                                                        # [win64]

build:
  number: 1
  skip: true  # [win and not py27]
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true

requirements:
  build:
    - autoconf        # [unix]
    - curl            # [unix]
    - expat           # [unix]
    - libiconv        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.*      # [unix]
    - 7za             # [win]

    # Workaround for conda-build issue.
    - python          # [win]
  run:
    - curl            # [unix]
    - expat           # [unix]
    - libiconv        # [unix]
    - openssl 1.0.*   # [unix]
    - zlib 1.2.*      # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  summary: distributed version control system

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
