{% set version = "2.51.0" %}
{% set name = "git" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{ version }}.tar.gz  # [not win]
    folder: code  # [not win]
    sha256: 3d531799d2cf2cac8e294ec6e3229e07bfca60dc6c783fe69e7712738bef7283  # [not win]
    patches:   # [not win]
      - 0001-macOS-Do-not-use-the-system-Wish-urgh.patch  # [not win]
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-manpages-{{ version }}.tar.gz  # [not win]
    folder: manpages  # [not win]
    sha256: c0e5d07f0051454df2cbdfac78e22e961e15ed5b09f10c6e58e315ca303492c2  # [not win]
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-htmldocs-{{ version }}.tar.gz  # [not win]
    folder: htmldocs  # [not win]
    sha256: b79d129def4a3cbcdb3ad8560ab71251f24fec8f27691d319f1e48095cc12fa2  # [not win]

  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
    folder: .  # [win64]
    sha256: a09b275d51ed3e829128e04cf4168fb54896cf6234bb30fecb8dc96a2bd321fa  # [win64]
  # Use this dummy source to tell our Windows signing process which binaries to skip. This is not actually used in the build.
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/Git-{{ version }}-64-bit.tar.bz2  # [win64]
    folder: git-64-bit  # [win64]
    sha256: 151bddf70e1115631e62bb05535b5e6726b3813e1f363953ad6b4e6697d96933  # [win64]

  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-arm64.7z.exe  # [win and arm64]
    folder: .  # [win and arm64]
    sha256: 0aacd4edf0c1715334a18725a947584652e1b34bddab63ac3f4a82c9f7c78e38  # [win and arm64]
  # Use this dummy source to tell our Windows signing process which binaries to skip. This is not actually used in the build.
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/Git-{{ version }}-arm64.tar.bz2  # [win and arm64]
    folder: git-arm64  # [win and arm64]
    sha256: 5c3bc6ca50ef6a7686832d2549e6e1b3b1060cf18322a2bbe064d4aec2f33904  # [win and arm64]


build:
  number: 2
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true
  missing_dso_whitelist: # [win]
    - '*'                # [win]
  no_link:
    - 'Menu/{{ name }}_menu.json'

requirements:
  build:
    - {{ stdlib('c') }}    # [unix]
    - {{ compiler('c') }}  # [unix]
    - autoconf             # [unix]
    - make                 # [unix]
    - 7zip                 # [win64]
  host:
    # https://github.com/git/git/blob/v2.51.0/INSTALL#L110
    - gettext {{ gettext }}    # [unix]
    - libcurl {{ libcurl }}    # [unix]
    - expat {{ expat }}        # [unix]
    - libiconv {{ libiconv }}  # [unix]
    - openssl {{ openssl }}    # [unix]
    - pcre2 {{ pcre2 }}        # [unix]
    - perl {{ perl }}          # [unix]
    - tk {{ tk }}              # [unix]
    - zlib {{ zlib }}          # [unix]
  run:
    - perl {{ perl.split(".")[0] }}.*  # [unix]
    # exact pin handled through run_exports
    - gettext   # [unix]
    - libcurl   # [unix]
    - expat     # [unix]
    - libiconv  # [unix]
    - openssl   # [unix]
    - pcre2     # [unix]
    - tk        # [unix]
    - zlib      # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - test -f $PREFIX/bin/gitk                              # [unix]
    - test -f $PREFIX/bin/git-credential-osxkeychain        # [osx]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # Git credential commands
    - git-credential-osxkeychain 2>&1 | grep -q usage  # [osx]

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]

    # confirm toplevel manpage
    - test -f $PREFIX/man/man1/git.1  # [not win]
    - test -f $PREFIX/share/man/man1/git.1  # [osx]

    # confirm toplevel html doc page
    - test -f $PREFIX/share/doc/git/index.html  # [not win]

about:
  home: https://git-scm.com/
  description: |
    Git is a distributed version control system that tracks changes in any set of computer files,
    usually used for coordinating work among programmers collaboratively developing source code during software development.
  license: GPL-2.0-or-later and LGPL-2.1-or-later
  license_file: code/COPYING  # [not win]
  license_url: https://raw.githubusercontent.com/git-for-windows/git/v2.40.1.windows.1/COPYING  # [win]
  license_family: OTHER
  summary: distributed version control system
  dev_url: https://github.com/git/git
  doc_url: https://git-scm.com/docs

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
    - ocefpaf
    - djsutherland
