{% set version = "2.31.1" %}
{% set extra_win_ver='1' %}

package:
  name: git
  version: {{ version }}

source:
  - url: https://www.kernel.org/pub/software/scm/git/git-{{ version }}.tar.xz    # [unix]
    sha256: 9f61417a44d5b954a5012b6f34e526a3336dcf5dd720e2bb7ada92ad8b3d6680     # [unix]
    patches:                                                                     # [unix]
      - 0001-macOS-Do-not-use-the-system-Wish-urgh.patch                         # [unix]
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.{{ extra_win_ver }}/MinGit-{{ version }}-busybox-32-bit.zip  # [win32]
    sha256: d3156def84d48bfacc6242f5386c3c7addc4d2752da078cab2da709f8820c9fc     # [win32]
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.{{ extra_win_ver }}/MinGit-{{ version }}-busybox-64-bit.zip  # [win64]
    sha256: d97a2f116692e78266fbf10976183d57a4193868df1a94de7d40d371e358b6f3     # [win64]
  - url: https://frippery.org/files/busybox/busybox-w32-FRP-3902-g61e53aa93.exe  # [win32]
    fn: busybox.exe                                                              # [win32]
  - url: https://frippery.org/files/busybox/busybox64.exe                        # [win64]
    fn: busybox.exe                                                              # [win64]

build:
  number: 0
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: True
  # 5/20/2021: run-exports library package pkgs/main::tk-8.6.10-hbc83047_0 and pcre-8.44-he6710b0_0 in requirements/run but it is not used 
  ignore_run_exports:
    - pcre
    - tk
    - openssl  # [osx]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - autoconf  # [unix]
    - make      # [unix]
  host:
    - libcurl   # [unix]
    - expat     # [unix]
    - libiconv  # [not linux and not win]
    - openssl   # [unix]
    - pcre      # [unix]
    - perl 5.*  # [unix]
    - tk        # [unix]
    - zlib      # [unix]
  run:
    - perl 5.*  # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - test -f $PREFIX/bin/gitk                              # [unix]
    - test -f $PREFIX/bin/git-credential-osxkeychain        # [osx]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Verify interactive support.
    - test -f $PREFIX/libexec/git-core/git-add--interactive  # [unix]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock
    - pushd git-feedstock
    - git submodule update --init
    - popd

    # Git credential commands
    - git-credential-osxkeychain 2>&1 | grep -q usage  # [osx]

    # Test that git interactive works
    - pushd $(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')  # [unix]
    - git init .                   # [unix]
    - echo hello > world           # [unix]
    - git add world                # [unix]
    - echo goodbye >> world        # [unix]
    - echo y | git add -p world    # [unix]
    - popd                         # [unix]

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  license_file: LICENSE.txt    # [win]
  summary: distributed version control system
  description: |
    Git is a free and open source distributed version control system designed
    to handle everything from small to very large projects with speed and
    efficiency.
  doc_url: https://git-scm.com/doc
  dev_url: https://github.com/git/git

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - pelson
    - scopatz
