{% set version = "2.55.0" %}
{% set name = "git" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{ version }}.tar.gz  # [not win]
    folder: code  # [not win]
    sha256: 0842dc384a23ac33ba3e570c4f3a8ded85963ee4713b1cd21153c3db41813d1e  # [not win]
    patches:   # [not win]
      - 0001-macOS-Do-not-use-the-system-Wish-urgh.patch  # [not win]
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-manpages-{{ version }}.tar.gz  # [not win]
    folder: manpages  # [not win]
    sha256: e1d56c160c55be805d339613d6c5cdb1269d5346a50d757c39135f1449e28ed5  # [not win]
  - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-htmldocs-{{ version }}.tar.gz  # [not win]
    folder: htmldocs  # [not win]
    sha256: 8cc302f07f4d246b556c4f4f57cdc0aa7f13a57f9b5c94629ff8ec26cddf66b5  # [not win]

  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
    folder: .  # [win64]
    sha256: dfa8cad3ce7e685b9bfbbb2125afcf7c68d4f53490426702ffac367dac62e928  # [win64]
  # Use this dummy source to tell our Windows signing process which binaries to skip. This is not actually used in the build.
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/Git-{{ version }}-64-bit.tar.bz2  # [win64]
    folder: git-64-bit  # [win64]
    sha256: 25bc3235291249f39bd463cd9fb86d9b4295b19d53d81af0238414bc68e16110  # [win64]

  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-arm64.7z.exe  # [win and arm64]
    folder: .  # [win and arm64]
    sha256: b1fe421482c6e5a1aa1135406d7eeb89adf5436b3e5af183cdcd6ffe3c6bc8f2  # [win and arm64]
  # Use this dummy source to tell our Windows signing process which binaries to skip. This is not actually used in the build.
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/Git-{{ version }}-arm64.tar.bz2  # [win and arm64]
    folder: git-arm64  # [win and arm64]
    sha256: 440998321e239588588ce5c8df1a45ffe99551691ac47d148dbbdae76776b582  # [win and arm64]


build:
  number: 0
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true
  missing_dso_whitelist: # [win]
    - '*'                # [win]
  no_link:
    - 'Menu/{{ name }}_menu.json'

requirements:
  build:
    - {{ stdlib('c') }}    # [unix]
    - {{ compiler('c') }}  # [unix]
    - autoconf             # [unix]
    - make                 # [unix]
  host:
    # https://github.com/git/git/blob/v2.55.0/INSTALL#L110
    - gettext {{ gettext }}    # [unix]
    - libcurl {{ libcurl }}    # [unix]
    - expat {{ expat }}        # [unix]
    - libiconv {{ libiconv }}  # [unix]
    - openssl {{ openssl }}    # [unix]
    - pcre2 {{ pcre2 }}        # [unix]
    - perl {{ perl }}          # [unix]
    - tk {{ tk }}              # [unix]
    - zlib {{ zlib }}          # [unix]
  run:
    - perl {{ perl.split(".")[0] }}.*  # [unix]
    # exact pin handled through run_exports
    - gettext   # [unix]
    - libcurl   # [unix]
    - expat     # [unix]
    - libiconv  # [unix]
    - openssl   # [unix]
    - pcre2     # [unix]
    - tk        # [unix]
    - zlib      # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - test -f $PREFIX/bin/gitk                              # [unix]
    - test -f $PREFIX/bin/git-credential-osxkeychain        # [osx]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # Git credential commands
    - git-credential-osxkeychain 2>&1 | grep -q usage  # [osx]

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]

    # confirm toplevel manpage
    - test -f $PREFIX/man/man1/git.1  # [not win]
    - test -f $PREFIX/share/man/man1/git.1  # [osx]

    # confirm toplevel html doc page
    - test -f $PREFIX/share/doc/git/index.html  # [not win]

about:
  home: https://git-scm.com/
  description: |
    Git is a distributed version control system that tracks changes in any set of computer files,
    usually used for coordinating work among programmers collaboratively developing source code during software development.
  license: GPL-2.0-or-later and LGPL-2.1-or-later
  license_file: COPYING
  license_family: OTHER
  summary: distributed version control system
  dev_url: https://github.com/git/git
  doc_url: https://git-scm.com/docs

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - scopatz
    - ocefpaf
    - djsutherland
