{% set version = "2.15.0" %}

package:
  name: git
  version: {{ version }}

source:
  url: https://github.com/git/git/archive/v{{ version }}.tar.gz                                                                   # [unix]
  sha256: 6b33b2b0e962338ac759a5102dfb777f280279b40ba0bde5dde0591b35520f2b     # [unix]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/MinGit-{{ version }}-busybox-32-bit.zip  # [win32]
  sha256: dcaea2b1721df5da464fe4b52fd6b3fbf1f60cf38320dee122fc0355161f7949                                                        # [win32]
  url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/MinGit-{{ version }}-busybox-64-bit.zip  # [win64]
  sha256: 300fda25b364ba692bae66406fcfc1a9700f9823693167fe29f809bf350c4803                                                        # [win64]

build:
  number: 0
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: True

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - autoconf        # [unix]
  host:
    - curl            # [unix]
    - expat           # [unix]
    - libiconv        # [not linux and not win]
    - openssl 1.0.*   # [unix]
    - zlib            # [unix]
    - perl 5.*        # [unix]
    - tk 8.*          # [unix]
  run:
    - curl            # [unix]
    - expat           # [unix]
    - libiconv        # [not linux and not win]
    - perl 5.*        # [unix]

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/git                               # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1    # [win]

    # Run git commands.
    - git --version
    - git clone https://github.com/conda-forge/git-feedstock

    # test completions
    - bash $PREFIX/share/bash-completion/completions/git  # [unix]

about:
  home: https://git-scm.com/
  license: GPL v2 and LGPL 2.1
  license_file: LICENSE.txt    # [win]
  summary: distributed version control system
  description: |
    Git is a free and open source distributed version control system designed
    to handle everything from small to very large projects with speed and
    efficiency.
  doc_url: https://git-scm.com/doc
  dev_url: https://github.com/git/git

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - pelson
    - scopatz
