travis:
  secure:
    BINSTAR_TOKEN: UxjwgwlpaSADCwO+7DETsrF0ADchPbcvsjMAyR6slo37H2uJYRMS5RKgcB1U2z82FkGFtduzWZH/EoVpg/vBBoKqx5iv9jH/rh/+/EuADUnuHf6JxoJ1nVLqtCtqwe4uiZ8u5G9luxcu4QN6N7N814mzmw7LL7gxmGyw6IjPJJ6Piryz1KBTKsHr3DC6iPMQoMUDBJ42iyTjRXjcVwKxfn0zKM6ofK0DR4Yg3+IjZ5JRXXlEC/6e1xYxckYZT/S9ICpCG6Od97heySupdtIIWnh94o9NJRV41ar71cvOpjD7aZAiE5Jh4+WUQWAcE50jj/WWtTXoHo01uet4egZcIfcwXvYcdtlhx/OWTN1vBj9jgm9iGHAR51Qcr82j160tIDwt2ZG7OScGk4VkDDL/paxxQXOGZNo/Y3GXI/sXaXyVaPt9+QloIdlKQHCkFy7CoWejWNEZIxoXvA02507ZdTiPrj/j6Kzu2abJG+oh6YDSvR8xPOF2hYcZmZNsKo/EGQsBphbTYA3Jzlp0QS2k+kYuUT14hqIO9ZEi/8wybn+5k/oV9xZ256KZBpYnBzGhFHR5csUenY76/6xAGpwYoti4UDTBtbTABLqjzgonrMyZ9amMFMSVqLKn+4EOtCDH0Tx3Jy+nW9u+v+w8xaAB0vXYvDZHO0avkbPrZ+fWxmU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
